#ifndef LL_APP_OIL_H_
#define LL_APP_OIL_H_
/* This is a ISR & ALARMCALLBACK header file generated by System Generator. */
#include "ll_std_app_oil.h"

/* FORWARDREF SOLUTION */

#define task1 0
#define task2 1
#define task3 2
#define test_os 0



#endif /*LL_APP_OIL_H_*/
