/* This is a C file generated by System Generator. */
#include "ll_app_oil.h"

/* FORWARDREF SOLUTION */

/*-----------------------------------------------------*/
volatile KRT_CONTEXT            context_cb[4];
volatile KRT_STACK              stack_cb[4];
volatile KRT_FN_POINTER         entry_cb[4]; 

volatile KRT_COMMON_STATIC_CB   static_common_cb[4];
volatile KRT_COMMON_DYNAMIC_CB  dynamic_common_cb[4];
volatile KRT_TASK_CB            task_table[4];
volatile KRT_ISR_CB             isr_table[1];
volatile KRT_READY_TASK_Q       ready_task_Q[4];
/*-----------------------------------------------------*/

/* MAIN STRUCT INITIALIZATION */

OIL_UINT8 OIL_PRIORITY_COUNT = 4;

OIL_UINT8 OIL_PRIORITY_SIZE[10]={ 10,10,10,10 };

OIL_UINT32 oarray_priorityQ_0[10];
OIL_UINT32 oarray_priorityQ_1[10];
OIL_UINT32 oarray_priorityQ_2[10];
OIL_UINT32 oarray_priorityQ_3[10];

OIL_UINT32 *oil_priorityQ_ref_list[4] ={
  oarray_priorityQ_0,
  oarray_priorityQ_1,
  oarray_priorityQ_2,
  oarray_priorityQ_3
};
/*-----------------------------------------------------*/
OIL_ENUM_OS_STATUS OS_ERROR_STATUS = oeSTANDARD_os_status;

OIL_BOOLEAN OS_USE_START_UP_HOOK = obTRUE;

OIL_BOOLEAN OS_USE_ERROR_HOOK = obFALSE;

OIL_BOOLEAN OS_USE_SHUT_DOWN_HOOK = obTRUE;

OIL_BOOLEAN OS_USE_PRE_TASK_HOOK = obFALSE;

OIL_BOOLEAN OS_USE_POST_TASK_HOOK = obFALSE;

OIL_BOOLEAN OS_USE_GET_SERVICE_ID = obFALSE;

OIL_BOOLEAN OS_USE_PARAMETER_ACCESS = obFALSE;

OIL_BOOLEAN OS_USE_RES_SCHEDULER = obTRUE;

OIL_BOOLEAN OS_USE_STACK_SHARE = obFALSE;

OIL_BOOLEAN OS_USE_STACK_CHECK = obFALSE;

OIL_BOOLEAN OS_ORTI_DEBUG_SUPPORT = obFALSE;

OIL_ENUM_OS_CC OS_CC = oeECC1_os_cc;
OIL_BOOLEAN OS_USE_MULTI_ACTIVATION = obFALSE;
OIL_BOOLEAN OS_USE_EXTENDED_TASK = obTRUE;

OIL_ENUM_OS_SCHEDULETYPE OS_SCHEDULETYPE = oeNON_os_scheduletype;

OIL_ENUM_OS_QMETHOD OS_QMETHOD = oeLIST_os_qmethod;



#if 0 /* OS object attr setting, function body should exsit outside of ll_app_oil.c */ 

void StartupHook(void) 
{ 
}

#endif


#if 1

void ErrorHook(StatusType error) 
{ 
}

#endif


#if 0 /* OS object attr setting, function body should exsit outside of ll_app_oil.c */ 

void ShutdownHook(StatusType error) 
{ 
}

#endif


#if 1

void PreTaskHook(void) 
{ 
}

#endif


#if 1

void PostTaskHook(void) 
{ 
}

#endif


OIL_UINT8 READYQ_QUEUE_SIZE = 10;
OIL_OS_TYPE test_os_d = {
  oeSTANDARD_os_status,
  obTRUE,
  obFALSE,
  obTRUE,
  obFALSE,
  obFALSE,
  obFALSE,
  obFALSE,
  obTRUE,
  obFALSE,
  obFALSE,
  obFALSE,
  oeECC1_os_cc,
  oeNON_os_scheduletype,
  oeLIST_os_qmethod,
  10
};
/*-------------------------------------------------------*/
OIL_APPMODE_ID oarray_task1_autostart_true_appmode[] = {
  /* OSDEFAULTAPPMODE */ 1
};
OIL_CNAB_TASK_AUTOSTART_TRUE ocnab_task1_autostart = {
  oarray_task1_autostart_true_appmode,
  1
};
OIL_UINT32 oarray_task1_stack[256/sizeof(OIL_UINT32)];
OIL_DECLARE_TASKFUNC(task1);
OIL_TASK_TYPE task1_d = {
  obTRUE,
  &ocnab_task1_autostart,
  2,
  1,
  oeNON_task_schedule,
  NULL,
  0,
  NULL,
  0,
  NULL,
  0,
  oeET_task_type,
  256,
  oarray_task1_stack,
  &(CALL_TASK_CNAME(task1))
};
/*-------------------------------------------------------*/
OIL_UINT32 oarray_task2_stack[256/sizeof(OIL_UINT32)];
OIL_DECLARE_TASKFUNC(task2);
OIL_TASK_TYPE task2_d = {
  obFALSE,
  0,
  1,
  1,
  oeNON_task_schedule,
  NULL,
  0,
  NULL,
  0,
  NULL,
  0,
  oeET_task_type,
  256,
  oarray_task2_stack,
  &(CALL_TASK_CNAME(task2))
};
/*-------------------------------------------------------*/
OIL_UINT32 oarray_task3_stack[256/sizeof(OIL_UINT32)];
OIL_DECLARE_TASKFUNC(task3);
OIL_TASK_TYPE task3_d = {
  obFALSE,
  0,
  3,
  1,
  oeNON_task_schedule,
  NULL,
  0,
  NULL,
  0,
  NULL,
  0,
  oeET_task_type,
  256,
  oarray_task3_stack,
  &(CALL_TASK_CNAME(task3))
};
/*-------------------------------------------------------*/
OIL_UINT8 OIL_TASK_COUNT=3;
OIL_TASK_TYPE *oil_task_ref_list[3] = {
  &task1_d,
  &task2_d,
  &task3_d
};

OIL_UINT8 OIL_OS_COUNT=1;
OIL_OS_TYPE *oil_os_ref_list[1] = {
  &test_os_d
};

OIL_UINT8 OIL_APPMODE_COUNT = 1;
AppModeType OSDEFAULTAPPMODE = 1;

/*--------------------------------------------------------*/
OIL_APPMODE_TYPE OSDEFAULTAPPMODE_d = {
  "OSDEFAULTAPPMODE"
};
/*--------------------------------------------------------*/

OIL_APPMODE_TYPE *oil_appmode_ref_list[1] = {
  &OSDEFAULTAPPMODE_d
};

OIL_UINT8 OIL_COMAPPMODE_COUNT = 0;

OIL_UINT8 OIL_ISR_COUNT = 0;
OIL_ISR_TYPE *oil_isr_ref_list[1] = {
	0
};

OIL_UINT8 OIL_MESSAGE_COUNT = 0;
OIL_MESSAGE_TYPE *oil_message_ref_list[1] = {
	0
};

OIL_UINT8 OIL_COUNTER_COUNT = 0;
OIL_COUNTER_TYPE *oil_counter_ref_list[1] = {
	0
};

CounterType SYSTEM_COUNTER = 0;

OIL_UINT8 OIL_ALARM_COUNT = 0;
OIL_ALARM_TYPE *oil_alarm_ref_list[1] = {
	0
};

OIL_UINT8 OIL_EVENT_COUNT = 0;
OIL_EVENT_TYPE *oil_event_ref_list[1] = {
	0
};

OIL_UINT8 OIL_COM_COUNT = 0;
OIL_COM_TYPE *oil_com_ref_list[1] = {
	0
};

UINT8 OIL_RESOURCE_COUNT = 0;
OIL_RESOURCE_TYPE *oil_resource_ref_list[1] = {
	0
};

ResourceType RES_SCHEDULER = 0;
